import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assests/styles/global.scss";

import { notFound } from "next/navigation";

import { Footer, Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

const locales = ["uz", "ru"];

export const metadata: Metadata = {
  title: "Munis do`koni",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
