import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assests/styles/global.scss";

import { useLocale } from "next-intl";
import { notFound } from "next/navigation";

import MainLayout from "@/Layouts/MainLayout";

const inter = Inter({ subsets: ["latin"] });

const locales = ["uz", "ru"];

export const metadata: Metadata = {
  title: "Munis do`koni",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = useLocale();

  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
